server:
  port: 8084
spring:
  application:
    name: MANAGEMENT-SERVICE
  datasource:
    username: bengal-tigers-management
    url: jdbc:mysql://*****/ManagementDB
    password: db-admin-bengal-tigers
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Calcutta
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://*****/eureka