spring:
  datasource:
    username: *****
    url: *****
    password: *****
  application:
    name: TASK-MANAGEMENT-SERVICE
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Calcutta
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: *****
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
server:
  port: 8085