server:
  port: 8086
spring:
  application:
    name: FIR-MANAGEMENT-SERVICE-LOCAL
  data:
    mongodb:
      uri: mongodb://*****/
      database: FIR_DB

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka