spring:
  datasource:
    username: bengal-tigers
    url: jdbc:mysql://*****/FeedbackSystemDB
    password: ******
  application:
    name: PS-PORTAL-SERVICE
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Calcutta
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
server:
  port: 8081