# This is a basic workflow to help you get started with Actions

name: Admin-Management-Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but  only for the "main" branch
  push:
    branches: ["admin-management-service"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: admin-management-service

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: check directory
        run: ls -a
      - name: Build with Maven
        run: mvn -B package --file /home/subhra/ksp-datathon/managementServiceRunner/_work/KSP-Datathon-Bengal-Tigers-PS-3/KSP-Datathon-Bengal-Tigers-PS-3/backendSourceCode/ManagementService/pom.xml
      - name: Killing the process on 8084
        run: sudo kill $(sudo lsof -i tcp:8084 | tr -s " " | cut -d " " -f 2 | sed -n 2p)
        continue-on-error: true
      - name: Running Jar
        run: sudo java -jar /home/subhra/ksp-datathon/managementServiceRunner/_work/KSP-Datathon-Bengal-Tigers-PS-3/KSP-Datathon-Bengal-Tigers-PS-3/backendSourceCode/ManagementService/target/ManagementService-0.0.1-SNAPSHOT.jar &
