# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and  support
# documentation.

name: Task-Management-Service-Workflow

on:
  push:
    branches: ["task-management-service"]

jobs:
  build:
    runs-on: task-management-service

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: check directory
        run: ls -a
      - name: Build with Maven
        run: mvn -B package --file /home/subhra/ksp-datathon/taskManagementService/_work/KSP-Datathon-Bengal-Tigers-PS-3/KSP-Datathon-Bengal-Tigers-PS-3/backendSourceCode/TaskManagementService/pom.xml
      - name: Killing the process on 8085
        run: sudo kill $(sudo lsof -i tcp:8085 | tr -s " " | cut -d " " -f 2 | sed -n 2p)
        continue-on-error: true
      - name: Running Jar
        run: sudo java -jar /home/subhra/ksp-datathon/taskManagementService/_work/KSP-Datathon-Bengal-Tigers-PS-3/KSP-Datathon-Bengal-Tigers-PS-3/backendSourceCode/TaskManagementService/target/TaskManagementService-0.0.1-SNAPSHOT.jar &
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
